# Generated by Django 6.1 on 2026-08-16 17:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_id', models.CharField(blank=True, help_text='Unique Complaint Reference ID', max_length=100, null=True, unique=True)),
                ('complaint_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('source', models.CharField(blank=True, max_length=150, null=True)),
                ('customer', models.CharField(blank=True, max_length=255, null=True)),
                ('api_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='API Name')),
                ('api_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='API Code')),
                ('batch_lot_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='Batch/Lot No')),
                ('manufacturing_date', models.DateField(blank=True, null=True)),
                ('retest_date', models.DateField(blank=True, null=True)),
                ('quantity_supplied', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('quantity_affected', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('complaint_category', models.CharField(blank=True, max_length=150, null=True)),
                ('complaint_description', models.TextField(blank=True, null=True)),
                ('specification', models.TextField(blank=True, null=True)),
                ('customer_result', models.TextField(blank=True, null=True)),
                ('coa_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='CoA No')),
                ('sample_available', models.BooleanField(blank=True, default=False, null=True)),
                ('investigation_root_cause', models.TextField(blank=True, null=True)),
                ('impacted_batches', models.JSONField(blank=True, default=list, help_text='List of impacted batch numbers')),
                ('capa_required', models.BooleanField(blank=True, default=False, null=True, verbose_name='CAPA Required')),
                ('capa_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='CAPA ID')),
                ('final_conclusion_disposition', models.TextField(blank=True, null=True)),
                ('qa_approval_closure', models.BooleanField(blank=True, default=False, null=True, verbose_name='QA Approval Closure')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Complaint',
                'verbose_name_plural': 'Complaints',
                'db_table': 'complaints',
                'ordering': ['-complaint_date', '-created_at'],
            },
        ),
    ]
