# Generated by Django 6.1 on 2026-08-17 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='complaint_id',
            field=models.CharField(default='API-CMP-2026-00479', help_text='Unique Complaint Reference ID', max_length=100, unique=True),
        ),
    ]
