# Generated by Django 6.1 on 2026-08-17 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_alter_complaint_complaint_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='complaint_id',
            field=models.CharField(default='complaint_id', help_text='Unique Complaint Reference ID', max_length=100, unique=True),
        ),
    ]
